version: '3.1'

volumes: 
  node_modules:
  yarn-cache:

services:
  redis:
    image: redis:alpine
    container_name: local-redis
    expose:
      - 6379
    ports:
      - "6379:6379"
  web:
    image: node:alpine
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - 'yarn-cache:/usr/local/share/.cache/yarn/'
    command: sh -c "cd app; yarn; yarn run dev"

